// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJmuWAVq6edm2E_IJws-neFarD-0IaT5w',
    appId: '1:448806411994:web:edb37b2806995dcaeb8fe3',
    messagingSenderId: '448806411994',
    projectId: 'chartingapp-168ed',
    authDomain: 'chartingapp-168ed.firebaseapp.com',
    databaseURL: 'https://chartingapp-168ed-default-rtdb.firebaseio.com',
    storageBucket: 'chartingapp-168ed.firebasestorage.app',
    measurementId: 'G-M25TJKGC4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCV7qW40OsK82qci-xFMzFp2-jWguF6eM',
    appId: '1:448806411994:android:fbe529d7bf5ceb56eb8fe3',
    messagingSenderId: '448806411994',
    projectId: 'chartingapp-168ed',
    databaseURL: 'https://chartingapp-168ed-default-rtdb.firebaseio.com',
    storageBucket: 'chartingapp-168ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9fsZ5DwP5aa7b6T66WbZRyGqznOIgPOo',
    appId: '1:448806411994:ios:9dfc41eb035af51beb8fe3',
    messagingSenderId: '448806411994',
    projectId: 'chartingapp-168ed',
    databaseURL: 'https://chartingapp-168ed-default-rtdb.firebaseio.com',
    storageBucket: 'chartingapp-168ed.firebasestorage.app',
    iosBundleId: 'com.example.chartapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9fsZ5DwP5aa7b6T66WbZRyGqznOIgPOo',
    appId: '1:448806411994:ios:9dfc41eb035af51beb8fe3',
    messagingSenderId: '448806411994',
    projectId: 'chartingapp-168ed',
    databaseURL: 'https://chartingapp-168ed-default-rtdb.firebaseio.com',
    storageBucket: 'chartingapp-168ed.firebasestorage.app',
    iosBundleId: 'com.example.chartapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJmuWAVq6edm2E_IJws-neFarD-0IaT5w',
    appId: '1:448806411994:web:c7510c3c8daa5b48eb8fe3',
    messagingSenderId: '448806411994',
    projectId: 'chartingapp-168ed',
    authDomain: 'chartingapp-168ed.firebaseapp.com',
    databaseURL: 'https://chartingapp-168ed-default-rtdb.firebaseio.com',
    storageBucket: 'chartingapp-168ed.firebasestorage.app',
    measurementId: 'G-VH9SXB4TKC',
  );
}
